import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scrollContent: {
        padding: 16,
        paddingBottom: 40,
    },
    container: { flex: 1, backgroundColor: "#f2f2f2", padding: 16 },
    supportContainer: { backgroundColor: "#f2f2f2", padding: 16, height: 200, borderRadius: 8, textAlignVertical: "top" },
    header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
    box: { backgroundColor: "#e0e0e0", padding: 8, borderRadius: 8 },
    cardBox: { padding: 8, borderRadius: 8, marginLeft: 30 },
    logo: { borderRadius: 8},
    cardImage: { marginTop: -20, marginBottom: -20, resizeMode:"contain", flex: 2 },
    menuText: {
        fontSize: 24,
        color: "#333",
    },
    overlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.2)",
        justifyContent: "flex-start",
        alignItems: "flex-end",
    },
    menuContainer: {
        backgroundColor: "#fff",
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 16,
        marginTop: 50,
        marginRight: 10,
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    menuItem: {
        paddingVertical: 8,
    },
    menuItemText: {
        fontSize: 16,
        color: "#333",
    },
    dropdownContainer: { marginBottom: 12, height: 50 },
    firstdropdown: { backgroundColor: "#ddd", borderColor: "#ddd", zIndex: 999 },
    dropdown: { backgroundColor: "#ddd", borderColor: "#ddd", zIndex: 1 },
    invoice: {
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "#eaeaea",
        borderRadius: 6,
        padding: 8,
        marginTop: 4,
    },
    invoiceDueBox: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#fff",
        width: 180,
    },
    overlapping: {
        alignItems: "center",
        marginTop:-30,
    },
    imageBox: {
        backgroundColor: "#ddd",
        // alignItems: "center",
    },
    card: {
        backgroundColor: "#ddd",
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        marginTop: 20,
    },
    whiteCard: {
        textAlign: "center",
        backgroundColor: "#fff",
        borderRadius: 8,
        marginTop: -12,
        marginBottom: 12,
        borderStyle: "solid",
        borderWidth: 2
    },
    title: { fontWeight: "600", marginBottom: 4, padding: 10 },
    amount: { textAlign: "center", fontWeight: "500", fontSize: 16, padding: 16 },
    subtext: { textAlign: "right", fontSize: 12, color: "#666", padding: 10 },
    transaction: {
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "#eaeaea",
        borderRadius: 6,
        padding: 8,
        marginTop: 4,
    },
    more: { alignItems: "flex-end", marginTop: 8 },
    moreText: { textAlign: "center", color:"#666", marginRight: 4 },
    button: {
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: "center",
        marginTop: 8,
    },
    primary: { backgroundColor: "black" },
    secondary: { borderWidth: 1, borderColor: "black" },
    buttonText: { color: "white", fontWeight: "600" },
    secondaryText: { color: "black", fontWeight: "600" },
    row: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderRadius: 10,
        paddingVertical: 14,
    },
    labelText: { fontSize: 14, fontWeight: "500", textAlign: "center", width: "90%" },
    text: { textAlign: "center", fontWeight: "600", marginBottom: 4},
    cardText: { textAlign: "left", fontWeight: "500", marginBottom: 4},
    longText: {
        flex: 2,
        fontSize: 14,
        color: "#333",
        fontWeight: "700",
        marginLeft: 5,
    },
    shortText: {
        flex: 1,
        fontSize: 14,
        color: "#333",
        fontWeight: "700",
        marginLeft: 5,
    },
    content: {
        flex: 1,
        justifyContent: "flex-start",
        padding: 20,
    },
});
